# Generated by Django 5.1.7 on 2026-08-30 05:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('agency', 'Agency')], default='free', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style_summary', models.TextField(blank=True, default='')),
                ('example_posts', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_slug', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=200)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('needs_attention', 'Needs attention'), ('broken', 'Broken')], default='healthy', max_length=20)),
                ('health_detail', models.CharField(blank=True, default='', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_values', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='omnipost_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/originals/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'GIF')], max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('story', 'Story'), ('short_video', 'Short video')], default='text', max_length=20)),
                ('base_text', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('base_media', models.ManyToManyField(blank=True, related_name='posts', to='omnipost_api.mediaasset')),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='omnipost_api.voiceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('story', 'Story'), ('short_video', 'Short video')], default='', max_length=20)),
                ('text_override', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('remote_id', models.CharField(blank=True, default='', max_length=200)),
                ('permalink', models.URLField(blank=True, default='')),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_targets', to='omnipost_api.channel')),
                ('media', models.ManyToManyField(blank=True, related_name='post_targets', to='omnipost_api.mediaasset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='omnipost_api.post')),
            ],
        ),
        migrations.CreateModel(
            name='PublishAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_class', models.CharField(blank=True, default='', max_length=30)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('state_step', models.CharField(blank=True, default='start', max_length=100)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('run_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='omnipost_api.posttarget')),
            ],
        ),
        migrations.CreateModel(
            name='QueueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('time_of_day', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slots', to='omnipost_api.channel')),
            ],
            options={
                'ordering': ['weekday', 'time_of_day'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='omnipost_api.organization')),
            ],
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to='omnipost_api.workspace'),
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('ai_text_generation', 'AI text generation'), ('ai_image_generation', 'AI image generation')], max_length=50)),
                ('period', models.CharField(default='lifetime', max_length=20)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('committed', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='omnipost_api.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter')], max_length=30)),
                ('encrypted_key', models.JSONField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_keys', to='omnipost_api.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='omnipost_api.workspace'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('contributor', 'Contributor'), ('viewer', 'Viewer'), ('client_reviewer', 'Client reviewer')], default='editor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='omnipost_api.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='omnipost_api.workspace'),
        ),
        migrations.AddField(
            model_name='channel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='omnipost_api.workspace'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='omnipost_api.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/renditions/%Y/%m/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='omnipost_api.mediaasset')),
            ],
            options={
                'unique_together': {('asset', 'profile')},
            },
        ),
        migrations.AddIndex(
            model_name='posttarget',
            index=models.Index(fields=['channel', 'status', 'run_at'], name='omnipost_ap_channel_e852e6_idx'),
        ),
        migrations.AddIndex(
            model_name='publishattempt',
            index=models.Index(fields=['status', 'run_at'], name='omnipost_ap_status_8c745f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publishattempt',
            unique_together={('post_target', 'epoch', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='queueslot',
            unique_together={('channel', 'weekday', 'time_of_day')},
        ),
        migrations.AlterUniqueTogether(
            name='usagecounter',
            unique_together={('workspace', 'feature', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='providerkey',
            unique_together={('workspace', 'provider')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['workspace', 'status'], name='omnipost_ap_workspa_cb13e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['workspace', 'connector_slug'], name='omnipost_ap_workspa_ccafec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['workspace', 'created_at'], name='omnipost_ap_workspa_a45760_idx'),
        ),
    ]
