# Generated by Django 5.1.7 on 2026-08-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='min_gap_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspace',
            name='approval_workflow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='BlackoutWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackout_windows', to='omnipost_api.channel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_windows', to='omnipost_api.workspace')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['workspace', 'starts_at', 'ends_at'], name='omnipost_ap_workspa_c268d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostTargetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('delay_after_s', models.PositiveIntegerField(default=0)),
                ('media', models.ManyToManyField(blank=True, related_name='post_target_parts', to='omnipost_api.mediaasset')),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='omnipost_api.posttarget')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('post_target', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('story', 'Story'), ('short_video', 'Short video')], default='text', max_length=20)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(blank=True, default='')),
                ('interval_hours', models.PositiveIntegerField()),
                ('next_variant_index', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='omnipost_api.channel')),
                ('media', models.ManyToManyField(blank=True, related_name='recurrence_rules', to='omnipost_api.mediaasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='omnipost_api.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='omnipost_ap_is_acti_68a092_idx')],
            },
        ),
    ]
