# Generated by Django 5.1.7 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posttext',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortformvideo',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyvideo',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
