# Generated by Django 5.1.7 on 2025-05-16 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('omnipost_api', '0002_postimage_published_posttext_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='post_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text Post'), ('IMAGE', 'Image Post'), ('VIDEO', 'Video Post'), ('SHORT_FORM_VIDEO', 'Short Form Video'), ('STORY_IMAGE', 'Story Image'), ('STORY_VIDEO', 'Story Video')], max_length=20, null=True),
        ),
    ]
