# Generated by Django 5.1.7 on 2026-09-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0002_channel_min_gap_minutes_channel_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_slug', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=300)),
                ('encrypted_client_secret', models.JSONField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_credentials', to='omnipost_api.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'connector_slug')},
            },
        ),
    ]
