# Generated by Django 5.1.7 on 2026-09-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0003_appcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttarget',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='omnipost_api.posttarget')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['post_target', 'fetched_at'], name='omnipost_ap_post_ta_fdb0df_idx')],
            },
        ),
    ]
