# Generated by Django 5.1.7 on 2025-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0003_alter_postimage_post_configs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminstance',
            name='salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
