# Generated by Django 5.1.7 on 2025-04-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0003_dummymodel_postimage_schedule_postvideo_schedule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
