# Generated by Django 5.1.7 on 2025-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0005_rename_remote_doc_docs_youtube_video_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docs',
            new_name='Doc',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
