# Generated by Django 5.1.7 on 2025-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0006_rename_docs_doc_rename_notifications_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='platform_instance',
        ),
    ]
