# Generated by Django 5.1.7 on 2025-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0007_remove_doc_platform_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
