# Generated by Django 5.1.7 on 2025-04-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0009_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
