# Generated by Django 5.1.7 on 2025-05-03 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0010_alter_stories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_configs', models.JSONField(blank=True, default=dict, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('platform_instances', models.ManyToManyField(to='omnipost_api.platforminstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Image',
                'verbose_name_plural': 'Story Images',
            },
        ),
        migrations.CreateModel(
            name='StoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_configs', models.JSONField(blank=True, default=dict, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('platform_instances', models.ManyToManyField(to='omnipost_api.platforminstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Video',
                'verbose_name_plural': 'Story Videos',
            },
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
