# Generated by Django 5.1.7 on 2025-05-05 05:49

import omnipost_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipost_api', '0011_storyimage_storyvideo_delete_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminstance',
            name='instance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[omnipost_api.models.validate_video_file]),
        ),
    ]
